import { Geist, Geist_Mono } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";

import ScrollToTop from "./scroller";
import Popup from "./components/popup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ValidationProvider } from "./context/ValidationContext";
import AuthProvider from "./components/AuthProvider";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <ValidationProvider>
            <Navbar />
            {/* <Popup /> */}
            {children}
            <Footer />
            <ScrollToTop />
          </ValidationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
